name: plunes
description: A new Flutter application.

version: 1.2.16+54

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intro_slider: ^1.2.0
  shared_preferences: ^0.5.2
  http: ^0.12.0+2
  modal_progress_hud: ^0.1.3
  date_format: ^1.0.6
  intl: ^0.16.0
  image_picker: ^0.6.0+8
  pinput: ^0.1.10
  percent_indicator: ^2.0.0
  flutter_webview_plugin: ^0.3.10+2
  url_launcher: ^5.0.3
  highlighter_coachmark: ^0.0.3
  transparent_image: ^0.1.0
  zoomable_image: ^1.3.1
  shimmer: ^1.0.0
  image_cropper: ^1.1.0
  super_tooltip: ^0.9.0
  date_picker_timeline: ^1.1.0
  share: ^0.6.3+1
  pdf_viewer_plugin: ^1.0.0+2
  location_permissions: ^2.0.0
  location: ^2.3.5
  geocoder: ^0.2.1
#  geocoder:
#    git:
#      url: https://github.com/Eimji/flutter_geocoder.git
#      ref: bc34cfe473bfd1934fe098bb7053248b75200241
  google_maps_flutter: ^0.5.21+7
  flutter_google_places: ^0.2.3
  firebase_messaging: 6.0.9
  connectivity: ^0.4.8+2
  fluttertoast: ^3.1.0
  file_picker: ^1.3.5
  open_file: ^2.0.3
  path: ^1.6.2
  flutter_spinkit: ^4.0.0
  dropdownfield: ^0.0.2
  path_provider: ^1.1.0
  bottom_navigation_badge: ^1.0.3
  flutter_typeahead: ^1.6.1
  flutter_local_notifications: ^0.8.4
  flutter_facebook_login: ^3.0.0
  cached_network_image: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
  uses-material-design: true
  assets:
    - assets/send.png
    - assets/gif/loading.gif
    - assets/send_active.png
    - assets/fb.png
    - assets/google.png
    - assets/city_icon.png
    - assets/test.png
    - assets/map_icon.png
    - assets/logo_test.png
    - assets/bid.png
    - assets/booking.png
    - assets/tick.png
    - assets/concern.png
    - assets/key.png
    - assets/account.png
    - assets/security.png
    - assets/all_payments.png
    - assets/payments2.png
    - assets/notification.png
    - assets/edit_profile.png
    - assets/change_pass.png
    - assets/logout.png
    - assets/logout2.png
    - assets/error_page.png
    - assets/images/enquiry/toggle_off.png
    - assets/images/enquiry/toggle_on.png

    - assets/images/plockr/plockr_selected.png
    - assets/images/plockr/plockr_unselected.png
    - assets/images/plockr/upload.png
    - assets/images/plockr/lock.png
    - assets/images/plockr/pdf_icon.png
    - assets/images/plockr/pdf.png
    - assets/images/plockr/doc.png

    - assets/images/nearyou/Dentist.png
    - assets/images/nearyou/Dermatology.png
    - assets/images/nearyou/Gynecology.png
    - assets/images/nearyou/Opthemalogist.png
    - assets/images/nearyou/Orthopedic.png
    - assets/images/nearyou/Pathology.png
    - assets/images/nearyou/Physiotherapy.png
    - assets/images/nearyou/Physotherepy.png
    - assets/images/nearyou/Radiology.png

    - assets/images/solution_result/selected.png
    - assets/images/solution_result/unselected.png

    - assets/images/refer/refer.png
    - assets/images/refer/cover.png
    - assets/images/refer/credit.png

    - assets/payments.png
    - assets/info.png
    - assets/heart.png
    - assets/consult.png
    - assets/doctor.png
    - assets/lawyer2.png
    - assets/soon.png
    - assets/no_img.png
    - assets/default_img.png
    - assets/prize.png
    - assets/bids.png
    - assets/consults.png
    - assets/searching.png
    - assets/logo_1.png
    - assets/logo_4.png
    - assets/logo1.png
    - assets/clock.png
    - assets/arrow.png
    - assets/payment_transfer.png
    - assets/utility.png
    - assets/images/bid/near_you.png
    - assets/images/login/first_user.png

    - assets/images/bottom_tabs/bid_active.png
    - assets/images/bottom_tabs/bid.png
    - assets/images/bottom_tabs/notification_active.png
    - assets/images/bottom_tabs/notification.png
    - assets/images/bottom_tabs/profile-active.png
    - assets/images/bottom_tabs/profile.png
    - assets/images/bottom_tabs/search_active.png
    - assets/images/bottom_tabs/search.png
    - assets/images/bottom_tabs/solution-active.png
    - assets/images/bottom_tabs/solution.png
    - assets/images/catalogue/catalog.png
    - assets/images/catalogue/edit.png
    - assets/images/catalogue/upload.png
    - assets/images/catalogue/view-sample.png

    - assets/images/sliders/bidding.png
    - assets/images/sliders/search.png
    - assets/images/sliders/solution.png
    - assets/images/sliders/near_you.png
    - assets/images/splash_final.jpg

    - assets/images/achievments/gradient/1.jpg
    - assets/images/achievments/gradient/2.jpg
    - assets/images/achievments/gradient/3.jpg
    - assets/images/achievments/gradient/4.jpg
    - assets/images/achievments/gradient/5.jpg
    - assets/images/achievments/gradient/6.jpg
    - assets/images/achievments/gradient/7.jpg
    - assets/images/achievments/gradient/8.jpg
    - assets/images/achievments/gradient/9.jpg
    - assets/images/achievments/gradient/10.jpg
    - assets/images/achievments/gradient/11.jpg
    - assets/images/achievments/achivement.png
    - assets/images/achievments/delete.png

    - assets/images/nav/about.png
    - assets/images/nav/logout.png
    - assets/images/nav/settings.png
    - assets/images/nav/appintment.png
    - assets/images/nav/availability.png
    - assets/images/nav/help.png
    - assets/images/nav/payments.png

    - assets/images/profile/college.png
    - assets/images/profile/education.png
    - assets/images/profile/expertise.png
    - assets/images/profile/location.png
    - assets/images/profile/star_1.png
    - assets/images/profile/arrow.png
    - assets/images/profile/add_utility.png
    - assets/images/profile/practise.png
    - assets/images/profile/qualification.png

    - assets/images/profile/calIcon.png
    - assets/images/profile/eduIcon.png
    - assets/images/profile/email_icon.png
    - assets/images/profile/phoneIcon.png
    - assets/images/profile/uniIcon.png


    - assets/images/bid/location.png
    - assets/images/bid/add_image.png
    - assets/images/bid/cancel.png
    - assets/images/bid/bid_active.png
    - assets/images/bid/failed.png
    - assets/images/bid/check.png
    - assets/images/bid/map.png
    - assets/images/bid/uncheck.png
    - assets/images/bid/tip.png

    - assets/images/solution/comment.png

    - assets/images/help/booking-appointment.png
    - assets/images/help/feedback.png
    - assets/images/help/online_solution.png
    - assets/images/help/other.png
    - assets/images/help/complain.png

    - assets/images/phonegrey.png
    - assets/images/tellIcongrey2.png
    - assets/images/walletgrey.png
    - assets/images/catIcon1.png
    - assets/images/calandergrey.png
    - assets/images/docIcon.png
    - assets/images/coupons.png
    - assets/images/bgElephantPopup.png
    - assets/images/elephant_image.png
    - assets/images/consultaion_icon.png
    - assets/images/test_icon.png
    - assets/images/light_test_icon.png
    - assets/images/check_icon.png
    - assets/images/blue_bg.png
    - assets/images/light_blue_bg.png
    - assets/images/shadow_consul_icon.png
    - assets/images/add_field_icon.png


permission:
  git:
  url: https://github.com/kamlesh9070/permission
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
